### ISSUE TITLE
ModuleNotFoundError: No module named 'steamfiles'

### ISSUE THREAD

**Issue by Kira-PH** [gasinvein/steam-desktop-updater#1]
I know what you're thinking. This n00b hasn't even got pip, let alone installed steamfiles.

I have. And I get this :(

`Traceback (most recent call last):`
`  File "./steam_desktop_updater.py", line 3, in <module>`
`    from steamfiles import appinfo`
`ModuleNotFoundError: No module named 'steamfiles'`

and...

`$ pip show steamfiles`
`Name: steamfiles`
`Version: 0.1.3`
`Summary: Python library for parsing the most common Steam file formats.`
`Home-page: https://github.com/leovp/steamfiles`
`Author: Leonid Runyshkin`
`Author-email: runyshkin@gmail.com`
`License: MIT`
`Location: /home/lelani/.local/lib/python2.7/site-packages`
`Requires: protobuf, protobuf3-to-dict`

**Comment by gasinvein** [comment]
Looks like you've installed python2 steamfiles module. Just install python3 version, e.g. pip3 install

**Comment by Kira-PH** [comment]
Thanks Filippe! Maybe you could put it in your readme.md?

**Comment by gasinvein** [comment]
I'll add setup.py and make the script installable via pip some day.

**Comment by gasinvein** [comment]
`steamfiles` was replaced  by `vdf` and `steam` modules in 65c8b5fc91191fbc5f40b78df4b40522ce7f917f
